export const DARK_MAP_STYLE = [
  { elementType: 'geometry', stylers: [{ color: '#0A0E1A' }] },
  { elementType: 'labels.text.fill', stylers: [{ color: '#8A9BBE' }] },
  { elementType: 'labels.text.stroke', stylers: [{ color: '#0A0E1A' }] },
  { featureType: 'administrative', elementType: 'geometry', stylers: [{ visibility: 'off' }] },
  { featureType: 'administrative.country', elementType: 'labels.text.fill', stylers: [{ color: '#4A5A7A' }] },
  { featureType: 'administrative.locality', elementType: 'labels.text.fill', stylers: [{ color: '#8A9BBE' }] },
  { featureType: 'poi', stylers: [{ visibility: 'off' }] },
  { featureType: 'poi.park', elementType: 'geometry', stylers: [{ color: '#0D1520' }] },
  { featureType: 'road', elementType: 'geometry', stylers: [{ color: '#111929' }] },
  { featureType: 'road', elementType: 'geometry.stroke', stylers: [{ color: '#1E2D3D' }] },
  { featureType: 'road', elementType: 'labels.text.fill', stylers: [{ color: '#4A5A7A' }] },
  { featureType: 'road.highway', elementType: 'geometry', stylers: [{ color: '#16213A' }] },
  { featureType: 'road.highway', elementType: 'geometry.stroke', stylers: [{ color: '#1E2D3D' }] },
  { featureType: 'road.highway', elementType: 'labels.text.fill', stylers: [{ color: '#6A7A9A' }] },
  { featureType: 'transit', stylers: [{ visibility: 'off' }] },
  { featureType: 'water', elementType: 'geometry', stylers: [{ color: '#060C16' }] },
  { featureType: 'water', elementType: 'labels.text.fill', stylers: [{ color: '#3A4A5A' }] },
];
